### ISSUE TITLE
Cannot open display when building headless

### ISSUE THREAD

**Issue by wouter-heerwegh** [xanderhendriks/docker-stm32cubeide#10]
Hi,

I'm using this docker image to build an stm32 project headless. I've seen there is an action for it as well, but I'm using a folder I need to include  that is not in the default Src/ or Inc/ directories.

My workflow looks as follows:
```shell
jobs:

  build:
    runs-on: ubuntu-latest
    container: xanderhendriks/stm32cubeide:9.0

    steps:
    - name: Update git
      run: |
        apt-get update
        apt-get install git -y

    - uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.TOKEN }}


    - name: Build project
      run: |
        stm32cubeide -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -import . -build all ${{ inputs.extra_includes }}
```

When using version 9.0 of the docker container, everything works fine, but I've tested all newer versions (up to 13.1), and all of them give the following error:
```
Stm32cubeide: Cannot open display
```
Does anyone know if there has there been a change in the way I should call a headless build?

**Edit**: Looking at the log file I can see the following:
```
java.lang.IllegalStateException: Workspace is already closed or not ready yet. Consider tracking the org.eclipse.core.resources.IWorkspace service (using your favorite technique, e.g. Declarative Services, ServiceTracker, Blueprint, ...) instead of calling the static method here to prevent such issues!
        at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:502)
        at org.eclipse.cdt.managedbuilder.internal.headlessbuilderapp.HeadlessBuilderWrapper.start(HeadlessBuilderWrapper.java:114)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```

**Comment by wouter-heerwegh** [comment]
I found [this issue](https://community.st.com/t5/stm32cubeide-mcus/stm32cubeide-1-15-1-headless-build-is-not-working/m-p/683242) on stm's forums. Apparently you can't run the command inside the project folder anymore.

I modified my workflow to the following:
```shell

jobs:

  build:
    runs-on: ubuntu-latest
    container: xanderhendriks/stm32cubeide:13.1

    steps:
    - name: Update git
      run: |
        apt-get update
        apt-get install git -y

    - uses: actions/checkout@v3
      with:
        path: ./project
        submodules: true
        token: ${{ secrets.TOKEN }}

    - name: Build project
      run: |
        cd ..
        stm32cubeide -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data ./project -importAll . -build all ${{ inputs.extra_includes }}
```
and it seems to work now, so I'm closing this issue

**Comment by xanderhendriks** [comment]
I'm glad you got it to work for you. I normally use the action as shown in this repo https://github.com/xanderhendriks/stm32-sample-application

**Comment by wouter-heerwegh** [comment]
Hi @xanderhendriks, thanks for the feedback. I indeed saw the action but I would need to do some testing to see if it would build with an extra (non-standard) folder inside the Core folder. I have a modules folder there that contains submodules of reusable code that also needs to be included.

**Comment by xanderhendriks** [comment]
It uses the original project file. So anything you configure Stm32CubeIde, which results in a working build, will also work with the action. We have multiple extra source and include directories we add to our projects.
